// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoe96qrc76k931OHK9PwO5i0-fqg-CqNo',
    appId: '1:980791935985:web:efadf6591cb8249d73ba50',
    messagingSenderId: '980791935985',
    projectId: 'authtutorial-7431b',
    authDomain: 'authtutorial-7431b.firebaseapp.com',
    storageBucket: 'authtutorial-7431b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzPiTXRfrDhif9gHHizMLLt6r5dEkgWd0',
    appId: '1:980791935985:android:1d26f9f49f6d01c673ba50',
    messagingSenderId: '980791935985',
    projectId: 'authtutorial-7431b',
    storageBucket: 'authtutorial-7431b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOb7P0lOHyNXylal9C0V-BBSAOk1yBmE',
    appId: '1:980791935985:ios:adb3671b5d49f69873ba50',
    messagingSenderId: '980791935985',
    projectId: 'authtutorial-7431b',
    storageBucket: 'authtutorial-7431b.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZOb7P0lOHyNXylal9C0V-BBSAOk1yBmE',
    appId: '1:980791935985:ios:adb3671b5d49f69873ba50',
    messagingSenderId: '980791935985',
    projectId: 'authtutorial-7431b',
    storageBucket: 'authtutorial-7431b.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoe96qrc76k931OHK9PwO5i0-fqg-CqNo',
    appId: '1:980791935985:web:74e9731264e23cdb73ba50',
    messagingSenderId: '980791935985',
    projectId: 'authtutorial-7431b',
    authDomain: 'authtutorial-7431b.firebaseapp.com',
    storageBucket: 'authtutorial-7431b.appspot.com',
  );
}
